### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by budiong** [caoqazwsx/MissZzzReader#3]
应用一打开就崩溃了
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.setAdapter(android.support.v4.view.PagerAdapter)' on a null object reference
        at com.zhao.myreader.ui.home.MainPrensenter.init(MainPrensenter.java:50)
        at com.zhao.myreader.ui.home.MainPrensenter.start(MainPrensenter.java:32)
        at com.zhao.myreader.ui.home.MainActivity.onCreate(MainActivity.java:48)

**Comment by 52game** [comment]
butterknife 升级一下

**Comment by zj614android** [comment]
> 升级

咋升？项目里写的版本是8.4.0

**Comment by zj614android** [comment]
另外给LZ留个言，这个博客是LZ的？看着不像，但写的原创，如果是就当我没说。
https://blog.csdn.net/qq_26851595/article/details/77336443

**Comment by 52game** [comment]
升到8.5.1
app的gradle里面
 `  implementation 'com.jakewharton:butterknife:8.5.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'`
project的gradle里面
` dependencies {
        classpath "com.jakewharton:butterknife-gradle-plugin:8.6.0"
    }`

**Comment by 52game** [comment]
这就是lz的吧 名字都一样

**Comment by zj614android** [comment]
> 升到8.5.1
> app的gradle里面
> ` implementation 'com.jakewharton:butterknife:8.5.1' annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'`
> project的gradle里面
> ` dependencies { classpath "com.jakewharton:butterknife-gradle-plugin:8.6.0" }`

感谢 已升 已经不崩溃了  但目前数据没书啊 ~~~

**Comment by 52game** [comment]
你试试看点搜索里面的“不朽凡人”

**Comment by zj614android** [comment]
> 这就是lz的吧 名字都一样

是就没事  我是看见了顺口一提  尊重lz劳动成果嘛

**Comment by zj614android** [comment]
> 你试试看点搜索里面的“不朽凡人”

朋友你那边有吗？ 我这边挨个点了 都没出阅读内容页呢

**Comment by 52game** [comment]
有且只有可能 不朽凡人 能搜出东西  看脸？
![Screenshot_20190322-113506](https://user-images.githubusercontent.com/25941837/54799113-b9f29900-4c96-11e9-9284-87688d5005d6.jpg)

**Comment by 52game** [comment]
有且只有 不朽凡人 能搜出东西 
![Screenshot_20190322-113506](https://user-images.githubusercontent.com/25941837/54799143-dabaee80-4c96-11e9-8a5b-75934ea69c1d.jpg)

**Comment by zj614android** [comment]
> 有且只有 不朽凡人 能搜出东西
> ![Screenshot_20190322-113506](https://user-images.githubusercontent.com/25941837/54799143-dabaee80-4c96-11e9-8a5b-75934ea69c1d.jpg)

谢谢  貌似是我这儿回调的时候报了个空指针进catch了 我看看

**Comment by EmerXiao** [comment]
大佬们能给我发送一个能正常运行的apk吗，想看下效果😔

**Comment by 52game** [comment]
> 大佬们能给我发送一个能正常运行的apk吗，想看下效果😔


[base(1).zip](https://github.com/caoqazwsx/MissZzzReader/files/3283942/base.1.zip)

**Comment by EmerXiao** [comment]
谢谢！




------------------ 原始邮件 ------------------
发件人: "52game"<notifications@github.com>; 
发送时间: 2019年6月13日(星期四) 中午11:02
收件人: "caoqazwsx/MissZzzReader"<MissZzzReader@noreply.github.com>; 
抄送: "aspirin"<1815166982@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [caoqazwsx/MissZzzReader] 崩溃 (#3)



 
大佬们能给我发送一个能正常运行的apk吗，想看下效果😔
  
base(1).zip

**Comment by Haaskk** [comment]
很无奈，这个开源的项目文件移植到android studio后，运行时里面的书籍等数据基本上都没了，并且相对应的apk里面也是，什么都没有，是因为长期没有维护的原因吗？
